# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'xuanke.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(400, 725)
        icon = QIcon()
        icon.addFile(u"D:/BlueStacks/ico/\u9010\u706b\u5341\u4e09\u82f1\u6840/Aponia.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.pushButton_1_1 = QPushButton(Form)
        self.pushButton_1_1.setObjectName(u"pushButton_1_1")
        self.pushButton_1_1.setGeometry(QRect(50, 30, 50, 50))
        self.pushButton_2_1 = QPushButton(Form)
        self.pushButton_2_1.setObjectName(u"pushButton_2_1")
        self.pushButton_2_1.setGeometry(QRect(100, 30, 50, 50))
        self.pushButton_3_1 = QPushButton(Form)
        self.pushButton_3_1.setObjectName(u"pushButton_3_1")
        self.pushButton_3_1.setGeometry(QRect(150, 30, 50, 50))
        self.pushButton_4_1 = QPushButton(Form)
        self.pushButton_4_1.setObjectName(u"pushButton_4_1")
        self.pushButton_4_1.setGeometry(QRect(200, 30, 50, 50))
        self.pushButton_5_1 = QPushButton(Form)
        self.pushButton_5_1.setObjectName(u"pushButton_5_1")
        self.pushButton_5_1.setGeometry(QRect(250, 30, 50, 50))
        self.pushButton_6_1 = QPushButton(Form)
        self.pushButton_6_1.setObjectName(u"pushButton_6_1")
        self.pushButton_6_1.setGeometry(QRect(300, 30, 50, 50))
        self.pushButton_7_1 = QPushButton(Form)
        self.pushButton_7_1.setObjectName(u"pushButton_7_1")
        self.pushButton_7_1.setGeometry(QRect(350, 30, 50, 50))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 10, 50, 20))
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(100, 10, 50, 20))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(150, 10, 50, 20))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(200, 10, 50, 20))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(250, 10, 50, 20))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(300, 10, 50, 20))
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(350, 10, 50, 20))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.pushButton_6_2 = QPushButton(Form)
        self.pushButton_6_2.setObjectName(u"pushButton_6_2")
        self.pushButton_6_2.setGeometry(QRect(300, 80, 50, 50))
        self.pushButton_2_2 = QPushButton(Form)
        self.pushButton_2_2.setObjectName(u"pushButton_2_2")
        self.pushButton_2_2.setGeometry(QRect(100, 80, 50, 50))
        self.pushButton_3_2 = QPushButton(Form)
        self.pushButton_3_2.setObjectName(u"pushButton_3_2")
        self.pushButton_3_2.setGeometry(QRect(150, 80, 50, 50))
        self.pushButton_4_2 = QPushButton(Form)
        self.pushButton_4_2.setObjectName(u"pushButton_4_2")
        self.pushButton_4_2.setGeometry(QRect(200, 80, 50, 50))
        self.pushButton_5_2 = QPushButton(Form)
        self.pushButton_5_2.setObjectName(u"pushButton_5_2")
        self.pushButton_5_2.setGeometry(QRect(250, 80, 50, 50))
        self.pushButton_7_2 = QPushButton(Form)
        self.pushButton_7_2.setObjectName(u"pushButton_7_2")
        self.pushButton_7_2.setGeometry(QRect(350, 80, 50, 50))
        self.pushButton_1_2 = QPushButton(Form)
        self.pushButton_1_2.setObjectName(u"pushButton_1_2")
        self.pushButton_1_2.setGeometry(QRect(50, 80, 50, 50))
        self.pushButton_6_3 = QPushButton(Form)
        self.pushButton_6_3.setObjectName(u"pushButton_6_3")
        self.pushButton_6_3.setGeometry(QRect(300, 130, 50, 50))
        self.pushButton_2_3 = QPushButton(Form)
        self.pushButton_2_3.setObjectName(u"pushButton_2_3")
        self.pushButton_2_3.setGeometry(QRect(100, 130, 50, 50))
        self.pushButton_3_3 = QPushButton(Form)
        self.pushButton_3_3.setObjectName(u"pushButton_3_3")
        self.pushButton_3_3.setGeometry(QRect(150, 130, 50, 50))
        self.pushButton_4_3 = QPushButton(Form)
        self.pushButton_4_3.setObjectName(u"pushButton_4_3")
        self.pushButton_4_3.setGeometry(QRect(200, 130, 50, 50))
        self.pushButton_5_3 = QPushButton(Form)
        self.pushButton_5_3.setObjectName(u"pushButton_5_3")
        self.pushButton_5_3.setGeometry(QRect(250, 130, 50, 50))
        self.pushButton_7_3 = QPushButton(Form)
        self.pushButton_7_3.setObjectName(u"pushButton_7_3")
        self.pushButton_7_3.setGeometry(QRect(350, 130, 50, 50))
        self.pushButton_1_3 = QPushButton(Form)
        self.pushButton_1_3.setObjectName(u"pushButton_1_3")
        self.pushButton_1_3.setGeometry(QRect(50, 130, 50, 50))
        self.pushButton_6_4 = QPushButton(Form)
        self.pushButton_6_4.setObjectName(u"pushButton_6_4")
        self.pushButton_6_4.setGeometry(QRect(300, 180, 50, 50))
        self.pushButton_2_4 = QPushButton(Form)
        self.pushButton_2_4.setObjectName(u"pushButton_2_4")
        self.pushButton_2_4.setGeometry(QRect(100, 180, 50, 50))
        self.pushButton_3_4 = QPushButton(Form)
        self.pushButton_3_4.setObjectName(u"pushButton_3_4")
        self.pushButton_3_4.setGeometry(QRect(150, 180, 50, 50))
        self.pushButton_4_4 = QPushButton(Form)
        self.pushButton_4_4.setObjectName(u"pushButton_4_4")
        self.pushButton_4_4.setGeometry(QRect(200, 180, 50, 50))
        self.pushButton_5_4 = QPushButton(Form)
        self.pushButton_5_4.setObjectName(u"pushButton_5_4")
        self.pushButton_5_4.setGeometry(QRect(250, 180, 50, 50))
        self.pushButton_7_4 = QPushButton(Form)
        self.pushButton_7_4.setObjectName(u"pushButton_7_4")
        self.pushButton_7_4.setGeometry(QRect(350, 180, 50, 50))
        self.pushButton_1_4 = QPushButton(Form)
        self.pushButton_1_4.setObjectName(u"pushButton_1_4")
        self.pushButton_1_4.setGeometry(QRect(50, 180, 50, 50))
        self.pushButton_4_6 = QPushButton(Form)
        self.pushButton_4_6.setObjectName(u"pushButton_4_6")
        self.pushButton_4_6.setGeometry(QRect(200, 280, 50, 50))
        self.pushButton_6_5 = QPushButton(Form)
        self.pushButton_6_5.setObjectName(u"pushButton_6_5")
        self.pushButton_6_5.setGeometry(QRect(300, 230, 50, 50))
        self.pushButton_3_8 = QPushButton(Form)
        self.pushButton_3_8.setObjectName(u"pushButton_3_8")
        self.pushButton_3_8.setGeometry(QRect(150, 380, 50, 50))
        self.pushButton_3_6 = QPushButton(Form)
        self.pushButton_3_6.setObjectName(u"pushButton_3_6")
        self.pushButton_3_6.setGeometry(QRect(150, 280, 50, 50))
        self.pushButton_2_8 = QPushButton(Form)
        self.pushButton_2_8.setObjectName(u"pushButton_2_8")
        self.pushButton_2_8.setGeometry(QRect(100, 380, 50, 50))
        self.pushButton_4_5 = QPushButton(Form)
        self.pushButton_4_5.setObjectName(u"pushButton_4_5")
        self.pushButton_4_5.setGeometry(QRect(200, 230, 50, 50))
        self.pushButton_6_6 = QPushButton(Form)
        self.pushButton_6_6.setObjectName(u"pushButton_6_6")
        self.pushButton_6_6.setGeometry(QRect(300, 280, 50, 50))
        self.pushButton_6_7 = QPushButton(Form)
        self.pushButton_6_7.setObjectName(u"pushButton_6_7")
        self.pushButton_6_7.setGeometry(QRect(300, 330, 50, 50))
        self.pushButton_2_7 = QPushButton(Form)
        self.pushButton_2_7.setObjectName(u"pushButton_2_7")
        self.pushButton_2_7.setGeometry(QRect(100, 330, 50, 50))
        self.pushButton_7_6 = QPushButton(Form)
        self.pushButton_7_6.setObjectName(u"pushButton_7_6")
        self.pushButton_7_6.setGeometry(QRect(350, 280, 50, 50))
        self.pushButton_5_6 = QPushButton(Form)
        self.pushButton_5_6.setObjectName(u"pushButton_5_6")
        self.pushButton_5_6.setGeometry(QRect(250, 280, 50, 50))
        self.pushButton_7_8 = QPushButton(Form)
        self.pushButton_7_8.setObjectName(u"pushButton_7_8")
        self.pushButton_7_8.setGeometry(QRect(350, 380, 50, 50))
        self.pushButton_7_5 = QPushButton(Form)
        self.pushButton_7_5.setObjectName(u"pushButton_7_5")
        self.pushButton_7_5.setGeometry(QRect(350, 230, 50, 50))
        self.pushButton_5_8 = QPushButton(Form)
        self.pushButton_5_8.setObjectName(u"pushButton_5_8")
        self.pushButton_5_8.setGeometry(QRect(250, 380, 50, 50))
        self.pushButton_1_8 = QPushButton(Form)
        self.pushButton_1_8.setObjectName(u"pushButton_1_8")
        self.pushButton_1_8.setGeometry(QRect(50, 380, 50, 50))
        self.pushButton_3_7 = QPushButton(Form)
        self.pushButton_3_7.setObjectName(u"pushButton_3_7")
        self.pushButton_3_7.setGeometry(QRect(150, 330, 50, 50))
        self.pushButton_1_7 = QPushButton(Form)
        self.pushButton_1_7.setObjectName(u"pushButton_1_7")
        self.pushButton_1_7.setGeometry(QRect(50, 330, 50, 50))
        self.pushButton_2_5 = QPushButton(Form)
        self.pushButton_2_5.setObjectName(u"pushButton_2_5")
        self.pushButton_2_5.setGeometry(QRect(100, 230, 50, 50))
        self.pushButton_3_5 = QPushButton(Form)
        self.pushButton_3_5.setObjectName(u"pushButton_3_5")
        self.pushButton_3_5.setGeometry(QRect(150, 230, 50, 50))
        self.pushButton_4_7 = QPushButton(Form)
        self.pushButton_4_7.setObjectName(u"pushButton_4_7")
        self.pushButton_4_7.setGeometry(QRect(200, 330, 50, 50))
        self.pushButton_4_8 = QPushButton(Form)
        self.pushButton_4_8.setObjectName(u"pushButton_4_8")
        self.pushButton_4_8.setGeometry(QRect(200, 380, 50, 50))
        self.pushButton_2_6 = QPushButton(Form)
        self.pushButton_2_6.setObjectName(u"pushButton_2_6")
        self.pushButton_2_6.setGeometry(QRect(100, 280, 50, 50))
        self.pushButton_1_6 = QPushButton(Form)
        self.pushButton_1_6.setObjectName(u"pushButton_1_6")
        self.pushButton_1_6.setGeometry(QRect(50, 280, 50, 50))
        self.pushButton_7_7 = QPushButton(Form)
        self.pushButton_7_7.setObjectName(u"pushButton_7_7")
        self.pushButton_7_7.setGeometry(QRect(350, 330, 50, 50))
        self.pushButton_5_7 = QPushButton(Form)
        self.pushButton_5_7.setObjectName(u"pushButton_5_7")
        self.pushButton_5_7.setGeometry(QRect(250, 330, 50, 50))
        self.pushButton_6_8 = QPushButton(Form)
        self.pushButton_6_8.setObjectName(u"pushButton_6_8")
        self.pushButton_6_8.setGeometry(QRect(300, 380, 50, 50))
        self.pushButton_5_5 = QPushButton(Form)
        self.pushButton_5_5.setObjectName(u"pushButton_5_5")
        self.pushButton_5_5.setGeometry(QRect(250, 230, 50, 50))
        self.pushButton_1_5 = QPushButton(Form)
        self.pushButton_1_5.setObjectName(u"pushButton_1_5")
        self.pushButton_1_5.setGeometry(QRect(50, 230, 50, 50))
        self.pushButton_4_10 = QPushButton(Form)
        self.pushButton_4_10.setObjectName(u"pushButton_4_10")
        self.pushButton_4_10.setGeometry(QRect(200, 480, 50, 50))
        self.pushButton_6_9 = QPushButton(Form)
        self.pushButton_6_9.setObjectName(u"pushButton_6_9")
        self.pushButton_6_9.setGeometry(QRect(300, 430, 50, 50))
        self.pushButton_3_12 = QPushButton(Form)
        self.pushButton_3_12.setObjectName(u"pushButton_3_12")
        self.pushButton_3_12.setGeometry(QRect(150, 580, 50, 50))
        self.pushButton_3_10 = QPushButton(Form)
        self.pushButton_3_10.setObjectName(u"pushButton_3_10")
        self.pushButton_3_10.setGeometry(QRect(150, 480, 50, 50))
        self.pushButton_2_12 = QPushButton(Form)
        self.pushButton_2_12.setObjectName(u"pushButton_2_12")
        self.pushButton_2_12.setGeometry(QRect(100, 580, 50, 50))
        self.pushButton_4_9 = QPushButton(Form)
        self.pushButton_4_9.setObjectName(u"pushButton_4_9")
        self.pushButton_4_9.setGeometry(QRect(200, 430, 50, 50))
        self.pushButton_6_10 = QPushButton(Form)
        self.pushButton_6_10.setObjectName(u"pushButton_6_10")
        self.pushButton_6_10.setGeometry(QRect(300, 480, 50, 50))
        self.pushButton_6_11 = QPushButton(Form)
        self.pushButton_6_11.setObjectName(u"pushButton_6_11")
        self.pushButton_6_11.setGeometry(QRect(300, 530, 50, 50))
        self.pushButton_2_11 = QPushButton(Form)
        self.pushButton_2_11.setObjectName(u"pushButton_2_11")
        self.pushButton_2_11.setGeometry(QRect(100, 530, 50, 50))
        self.pushButton_7_10 = QPushButton(Form)
        self.pushButton_7_10.setObjectName(u"pushButton_7_10")
        self.pushButton_7_10.setGeometry(QRect(350, 480, 50, 50))
        self.pushButton_5_10 = QPushButton(Form)
        self.pushButton_5_10.setObjectName(u"pushButton_5_10")
        self.pushButton_5_10.setGeometry(QRect(250, 480, 50, 50))
        self.pushButton_7_12 = QPushButton(Form)
        self.pushButton_7_12.setObjectName(u"pushButton_7_12")
        self.pushButton_7_12.setGeometry(QRect(350, 580, 50, 50))
        self.pushButton_7_9 = QPushButton(Form)
        self.pushButton_7_9.setObjectName(u"pushButton_7_9")
        self.pushButton_7_9.setGeometry(QRect(350, 430, 50, 50))
        self.pushButton_5_12 = QPushButton(Form)
        self.pushButton_5_12.setObjectName(u"pushButton_5_12")
        self.pushButton_5_12.setGeometry(QRect(250, 580, 50, 50))
        self.pushButton_1_12 = QPushButton(Form)
        self.pushButton_1_12.setObjectName(u"pushButton_1_12")
        self.pushButton_1_12.setGeometry(QRect(50, 580, 50, 50))
        self.pushButton_3_11 = QPushButton(Form)
        self.pushButton_3_11.setObjectName(u"pushButton_3_11")
        self.pushButton_3_11.setGeometry(QRect(150, 530, 50, 50))
        self.pushButton_1_11 = QPushButton(Form)
        self.pushButton_1_11.setObjectName(u"pushButton_1_11")
        self.pushButton_1_11.setGeometry(QRect(50, 530, 50, 50))
        self.pushButton_2_9 = QPushButton(Form)
        self.pushButton_2_9.setObjectName(u"pushButton_2_9")
        self.pushButton_2_9.setGeometry(QRect(100, 430, 50, 50))
        self.pushButton_3_9 = QPushButton(Form)
        self.pushButton_3_9.setObjectName(u"pushButton_3_9")
        self.pushButton_3_9.setGeometry(QRect(150, 430, 50, 50))
        self.pushButton_4_11 = QPushButton(Form)
        self.pushButton_4_11.setObjectName(u"pushButton_4_11")
        self.pushButton_4_11.setGeometry(QRect(200, 530, 50, 50))
        self.pushButton_4_12 = QPushButton(Form)
        self.pushButton_4_12.setObjectName(u"pushButton_4_12")
        self.pushButton_4_12.setGeometry(QRect(200, 580, 50, 50))
        self.pushButton_2_10 = QPushButton(Form)
        self.pushButton_2_10.setObjectName(u"pushButton_2_10")
        self.pushButton_2_10.setGeometry(QRect(100, 480, 50, 50))
        self.pushButton_1_10 = QPushButton(Form)
        self.pushButton_1_10.setObjectName(u"pushButton_1_10")
        self.pushButton_1_10.setGeometry(QRect(50, 480, 50, 50))
        self.pushButton_7_11 = QPushButton(Form)
        self.pushButton_7_11.setObjectName(u"pushButton_7_11")
        self.pushButton_7_11.setGeometry(QRect(350, 530, 50, 50))
        self.pushButton_5_11 = QPushButton(Form)
        self.pushButton_5_11.setObjectName(u"pushButton_5_11")
        self.pushButton_5_11.setGeometry(QRect(250, 530, 50, 50))
        self.pushButton_6_12 = QPushButton(Form)
        self.pushButton_6_12.setObjectName(u"pushButton_6_12")
        self.pushButton_6_12.setGeometry(QRect(300, 580, 50, 50))
        self.pushButton_5_9 = QPushButton(Form)
        self.pushButton_5_9.setObjectName(u"pushButton_5_9")
        self.pushButton_5_9.setGeometry(QRect(250, 430, 50, 50))
        self.pushButton_1_9 = QPushButton(Form)
        self.pushButton_1_9.setObjectName(u"pushButton_1_9")
        self.pushButton_1_9.setGeometry(QRect(50, 430, 50, 50))
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 30, 50, 20))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 50, 50, 10))
        self.label_9.setMouseTracking(True)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 60, 50, 10))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 80, 50, 20))
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(Form)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(0, 100, 50, 10))
        self.label_12.setMouseTracking(True)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(Form)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(0, 110, 50, 10))
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(Form)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 130, 50, 20))
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_15 = QLabel(Form)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 150, 50, 10))
        self.label_15.setMouseTracking(True)
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(Form)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 160, 50, 10))
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(Form)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 180, 50, 20))
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(Form)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 200, 50, 10))
        self.label_18.setMouseTracking(True)
        self.label_18.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(Form)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(0, 210, 50, 10))
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(Form)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(0, 230, 50, 20))
        self.label_20.setAlignment(Qt.AlignCenter)
        self.label_21 = QLabel(Form)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(0, 250, 50, 10))
        self.label_21.setMouseTracking(True)
        self.label_21.setAlignment(Qt.AlignCenter)
        self.label_22 = QLabel(Form)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(0, 260, 50, 10))
        self.label_22.setAlignment(Qt.AlignCenter)
        self.label_23 = QLabel(Form)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(0, 280, 50, 20))
        self.label_23.setAlignment(Qt.AlignCenter)
        self.label_24 = QLabel(Form)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(0, 300, 50, 10))
        self.label_24.setMouseTracking(True)
        self.label_24.setAlignment(Qt.AlignCenter)
        self.label_25 = QLabel(Form)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(0, 310, 50, 10))
        self.label_25.setAlignment(Qt.AlignCenter)
        self.label_26 = QLabel(Form)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(0, 330, 50, 20))
        self.label_26.setAlignment(Qt.AlignCenter)
        self.label_27 = QLabel(Form)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(0, 350, 50, 10))
        self.label_27.setMouseTracking(True)
        self.label_27.setAlignment(Qt.AlignCenter)
        self.label_28 = QLabel(Form)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(0, 360, 50, 10))
        self.label_28.setAlignment(Qt.AlignCenter)
        self.label_29 = QLabel(Form)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(0, 380, 50, 20))
        self.label_29.setAlignment(Qt.AlignCenter)
        self.label_30 = QLabel(Form)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(0, 400, 50, 10))
        self.label_30.setMouseTracking(True)
        self.label_30.setAlignment(Qt.AlignCenter)
        self.label_31 = QLabel(Form)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(0, 410, 50, 10))
        self.label_31.setAlignment(Qt.AlignCenter)
        self.label_32 = QLabel(Form)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(0, 430, 50, 20))
        self.label_32.setAlignment(Qt.AlignCenter)
        self.label_33 = QLabel(Form)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(0, 450, 50, 10))
        self.label_33.setMouseTracking(True)
        self.label_33.setAlignment(Qt.AlignCenter)
        self.label_34 = QLabel(Form)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(0, 460, 50, 10))
        self.label_34.setAlignment(Qt.AlignCenter)
        self.label_35 = QLabel(Form)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(0, 480, 50, 20))
        self.label_35.setAlignment(Qt.AlignCenter)
        self.label_36 = QLabel(Form)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(0, 500, 50, 10))
        self.label_36.setMouseTracking(True)
        self.label_36.setAlignment(Qt.AlignCenter)
        self.label_37 = QLabel(Form)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(0, 510, 50, 10))
        self.label_37.setAlignment(Qt.AlignCenter)
        self.label_38 = QLabel(Form)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(0, 530, 50, 20))
        self.label_38.setAlignment(Qt.AlignCenter)
        self.label_39 = QLabel(Form)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(0, 550, 50, 10))
        self.label_39.setMouseTracking(True)
        self.label_39.setAlignment(Qt.AlignCenter)
        self.label_40 = QLabel(Form)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(0, 560, 50, 10))
        self.label_40.setAlignment(Qt.AlignCenter)
        self.label_41 = QLabel(Form)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(0, 580, 50, 20))
        self.label_41.setAlignment(Qt.AlignCenter)
        self.label_42 = QLabel(Form)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(0, 600, 50, 10))
        self.label_42.setMouseTracking(True)
        self.label_42.setAlignment(Qt.AlignCenter)
        self.label_43 = QLabel(Form)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(0, 610, 50, 10))
        self.label_43.setAlignment(Qt.AlignCenter)
        self.pushButton_save = QPushButton(Form)
        self.pushButton_save.setObjectName(u"pushButton_save")
        self.pushButton_save.setGeometry(QRect(150, 655, 100, 50))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u8bfe\u8868", None))
        self.pushButton_1_1.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_1.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_1.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_1.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_1.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_1.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_1.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u5468\u4e00", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u5468\u4e8c", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u5468\u4e09", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u5468\u56db", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u5468\u4e94", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u5468\u516d", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"\u5468\u65e5", None))
        self.pushButton_6_2.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_2.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_2.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_2.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_2.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_2.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_2.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_3.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_3.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_3.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_3.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_3.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_3.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_3.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_4.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_4.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_4.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_4.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_4.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_4.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_4.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_6.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_5.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_8.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_6.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_8.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_5.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_6.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_7.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_7.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_6.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_6.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_8.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_5.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_8.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_8.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_7.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_7.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_5.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_5.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_7.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_8.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_6.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_6.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_7.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_7.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_8.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_5.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_5.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_10.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_9.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_12.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_10.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_12.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_9.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_10.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_11.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_11.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_10.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_10.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_12.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_9.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_12.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_12.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_11.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_11.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_9.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_3_9.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_11.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_4_12.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_2_10.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_10.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_7_11.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_11.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_6_12.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_5_9.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.pushButton_1_9.setText(QCoreApplication.translate("Form", u"\u672a\u9009\u4e2d", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"1", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">08\uff1a00</span></p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">08\uff1a50</span></p></body></html>", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"2", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">09\uff1a00</span></p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">09\uff1a50</span></p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"3", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">10\uff1a10</span></p></body></html>", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">11\uff1a00</span></p></body></html>", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"4", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">11\uff1a10</span></p></body></html>", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">12\uff1a00</span></p></body></html>", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"5", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">13\uff1a30</span></p></body></html>", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">14\uff1a20</span></p></body></html>", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"6", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">14\uff1a30</span></p></body></html>", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">15\uff1a20</span></p></body></html>", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"7", None))
        self.label_27.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">15\uff1a30</span></p></body></html>", None))
        self.label_28.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">16\uff1a20</span></p></body></html>", None))
        self.label_29.setText(QCoreApplication.translate("Form", u"8", None))
        self.label_30.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">16\uff1a30</span></p></body></html>", None))
        self.label_31.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">17\uff1a20</span></p></body></html>", None))
        self.label_32.setText(QCoreApplication.translate("Form", u"9", None))
        self.label_33.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">17\uff1a30</span></p></body></html>", None))
        self.label_34.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">18\uff1a20</span></p></body></html>", None))
        self.label_35.setText(QCoreApplication.translate("Form", u"10", None))
        self.label_36.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">18\uff1a30</span></p></body></html>", None))
        self.label_37.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">19\uff1a20</span></p></body></html>", None))
        self.label_38.setText(QCoreApplication.translate("Form", u"11", None))
        self.label_39.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">19\uff1a30</span></p></body></html>", None))
        self.label_40.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">20\uff1a20</span></p></body></html>", None))
        self.label_41.setText(QCoreApplication.translate("Form", u"12", None))
        self.label_42.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">20\uff1a30</span></p></body></html>", None))
        self.label_43.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:7pt;\">21\uff1a20</span></p></body></html>", None))
        self.pushButton_save.setText(QCoreApplication.translate("Form", u"\u786e\u5b9a\u4fdd\u5b58", None))
    # retranslateUi

